#!/bin/bash

# Use goobook to query google contacts
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/lbdb

m_goobook_query ()
{
    goobook query "$@" | grep -v '^$' | sed -e 's/$/ - goobook/'
}
