#!/bin/bash

# get app image for Ubuntu
[[ ! $(type -P "nvim") ]] && {
  sudo apt update
  sudo apt install snapd
  sudo snap install nvim --classic
}
sudo apt-get -y install build-essential tmux python3 python3-dev ruby libluajit-5.1-dev luajit ruby-dev nodejs npm ripgrep python3-venv zsh fzy

mkdir -p ~/.local/share/nvim/{bundle,lspconfig,shada,undo}
mkdir -p ~/.config/nvim/{autoload,colors}
curl -fsSL -o ~/.vimrc https://raw.githubusercontent.com/adragomir/dotfiles/master/.vimrc
ln -s ~/.vimrc ~/.config/nvim/init.vim
curl -fsSL -o ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/adragomir/dotfiles/master/.vim/autoload/plug.vim
curl -fsSL -o ~/.config/nvim/colors/monochrome.vim https://raw.githubusercontent.com/adragomir/dotfiles/master/.vim/colors/monochrome.vim
mkdir -p ~/.zsh
mkdir -p ~/.history
curl -fsSL -o ~/.zshrc https://raw.githubusercontent.com/adragomir/dotfiles/master/.zshrc
curl -fsSL -o ~/.zsh/async https://raw.githubusercontent.com/adragomir/dotfiles/master/.zsh/async
curl -fsSL -o ~/.zsh/golang.plugin.zsh https://raw.githubusercontent.com/adragomir/dotfiles/master/.zsh/golang.plugin.zsh
curl -fsSL -o ~/.zsh/url-tools.plugin.zsh https://raw.githubusercontent.com/adragomir/dotfiles/master/.zsh/url-tools.plugin.zsh
mkdir -p ~/.tmux/{plugins,resurrect}
curl -fsSL -o ~/.tmux.conf https://raw.githubusercontent.com/adragomir/dotfiles/master/.tmux.conf
pip3 install neovim
sudo gem install neovim
sudo npm install -g neovim
chsh -s /usr/bin/zsh
curl -fsSL https://fnm.vercel.app/install | bash
curl -fsSL -o frum-v0.1.2-x86_64-unknown-linux-musl.tar.gz https://github.com/TaKO8Ki/frum/releases/download/v0.1.2/frum-v0.1.2-x86_64-unknown-linux-musl.tar.gz
tar zxf frum-v0.1.2-x86_64-unknown-linux-musl.tar.gz
mv frum-v0.1.2-x86_64-unknown-linux-musl /usr/local/bin/frum
rm -rf frum*
chmod +x /usr/local/bin/frum

