#!/bin/bash

# get app image for Ubuntu
[[ ! $(type -P "nvim") ]] && {
  sudo apt update
  sudo apt-get install build-essential tmux python3 ruby libluajit-5.1-dev luajit ruby-dev
  sudo apt install snapd
  sudo snap install nvim --classic
}

mkdir -p ~/.local/share/nvim/{bundle,lspconfig,shada,undo}
mkdir -p ~/.config/nvim/{autoload,colors}
curl -fsSL -o ~/.vimrc https://raw.githubusercontent.com/adragomir/dotfiles/master/.vimrc
ln -s ~/.vimrc ~/.config/nvim/init.vim
curl -fsSL -o ~/.config/nvim/autoload/plug.vim https://raw.githubusercontent.com/adragomir/dotfiles/master/.vim/autoload/plug.vim
curl -fsSL -o ~/.config/nvim/colors/monochrome.vim https://raw.githubusercontent.com/adragomir/dotfiles/master/.vim/colors/monochrome.vim
mkdir -p ~/.zsh
curl -fsSL -o ~/.zshrc https://raw.githubusercontent.com/adragomir/dotfiles/master/.zshrc
mkdir -p ~/.tmux/{plugins,resurrect}
curl -fsSL -o ~/.tmux.conf https://raw.githubusercontent.com/adragomir/dotfiles/master/.tmux.conf
pip3 install neovim
sudo gem install neovim
